require "user.options"
require "user.keymaps"
require "user.plugins"
vim.cmd "colorscheme onedark"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.lualine"
require "user.autopairs"
--require "user.gitsigns"
require "user.nvim-tree"
require "user.which-key"
